### PR TITLE
Add longhorn installation playbook and role

### PR DESCRIPTION
**Pull request by johnworth**
SSIA

### CODE REVIEW

**Review by slr71 — APPROVED** [review]
Looks good to me!

**Comment by ianmcorvidae** [comment]
I wasn't sure if we have pre-existing stuff that sets up the longhorn installation requirements: https://longhorn.io/docs/1.6.0/deploy/install/#installation-requirements

That's often been the annoying part when I've been setting it up, haha

**Comment by johnworth** [comment]
@ianmcorvidae Ooh, good catch, I'll work on that next.

**Comment by johnworth** [comment]
@ianmcorvidae okay, I've added steps to install the requirements for longhorn to the kubernetes nodes role. Can you double check them when you have a chance?

**Review by ianmcorvidae — APPROVED** [review]
Looks good to me, as far as I can tell! Looks like the prereq stuff was fairly easy, so glad to see that for sure.

**Pull request merged**
