### PR TITLE
HAProxy

### PR DESCRIPTION
**Pull request by ianmcorvidae**
This should, hopefully, add a simple HAProxy setup for the DE. Some things this doesn't handle: redirecting old URLs to the current one (e.g. newqa -> qa), and currently hardcodes qa as the URL. I'll work on those (at least the latter), but wanted to get the structure of it up for potential review this week.

### CODE REVIEW

**Review by slr71 — COMMENTED** [review]
I The playbook and role both look good. I was thinking that a quick blurb in the README about group variables used by the role might be helpful, but that's the only suggestion that I had. I think we can :shipit: whenever you're ready.

**Review by slr71 — APPROVED** [review]
I forgot to click Approve before submitting my last review. 😁

**Comment by ianmcorvidae** [comment]
Cool, thanks for the review! I'll try to copy a README format that looks informative and then merge, haha. I realized I also need to push a change to the inventory repository, which I'll probably just do (it just adds the `de_proxy` group that these playbooks use).

**Comment by slr71** [comment]
That sounds good to me. I've been pushing updates to the inventory repository directly too.

**Pull request merged**
